In [1]:
import sqlite3
import pandas as pd

con = sqlite3.connect("data/ntsb.db")
pd.read_sql_query("SELECT COUNT(*) FROM accidents WHERE event_year = 2019", con)

   COUNT(*)
0      1308

In [4]:
pd.read_sql_query("""
    SELECT UPPER(make) AS make_norm, COUNT(*) AS n
    FROM accidents
    GROUP BY UPPER(make)
    ORDER BY n DESC
    LIMIT 10
""", con)

             make_norm     n
0               CESSNA  1852
1                PIPER  1116
2                BEECH   402
3                 BELL   165
4               BOEING   123
5               MOONEY    91
6  ROBINSON HELICOPTER    79
7   CIRRUS DESIGN CORP    79
8             ROBINSON    77
9      AIR TRACTOR INC    77

In [5]:
pd.read_sql_query("SELECT COUNT(*) FROM accidents WHERE fatal_injury_count > 0", con)

   COUNT(*)
0      1122

In [ ]:
pd.read_sql_query("SELECT COUNT(*) FROM accidents WHERE fatal_injury_count > 0", con)